name: e2e

on:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Clojure CLI
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest
      - name: Build dataset
        run: clojure -T:build publish
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Playwright
        run: |
          npm install --no-save playwright
          npx playwright install --with-deps chromium
      - name: Start static server
        run: python3 -m http.server 8080 -d public &
      - name: Run test
        run: node e2e/test.js
